version: '3.8'

services:
  backend:
    build: .
    container_name: backend_container
    ports:
      - '3100:3000'
    environment:
      PORT: ${PORT} 
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER} 
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME} 
    depends_on:
      - postgres
    networks:
      - my_network 
    develop:
      watch:
        - action: rebuild  # akan membangun ulang ketika file berubah
          path: ./         # pantau seluruh direktori
          ignore:          # abaikan file-file yang tidak relevan
            - node_modules/
            - .git/
            - pgdata/

  postgres:
    image: postgres:14
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5400:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5150:80'
    depends_on:
      - postgres
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
